name: ArgoCD Application Creation

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      path:
        required: true
        type: string
      dest-server:
        required: true
        type: string
      dest-namespace:
        required: true
        type: string
      revision:
        required: true
        type: string

    secrets:
      ARGOCD_SERVER:
        required: true
      ARGOCD_USERNAME:
        required: true
      ARGOCD_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up ArgoCD CLI
      - name: Set up ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v2.9.7/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          mv argocd-linux-amd64 /usr/local/bin/argocd
      
      # Step 3: Authenticate with ArgoCD server
      - name: Authenticate with ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
      
      # Step 4: Create the ArgoCD application
      - name: Create ArgoCD Application
        run: |
          argocd app create my-app \
            --repo ${{ inputs.repo }} \
            --path ${{ inputs.path }} \
            --dest-server ${{ inputs.dest-server }} \
            --dest-namespace ${{ inputs.dest-namespace }} \
            --sync-policy automated \
            --revision ${{ inputs.revision }}
        
      # Step 5: Wait for the application to be deployed
      - name: Wait for the application to be deployed
        run: |
          argocd app wait my-app --timeout 600