name: CD

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: node-app
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub_key: ${{ secrets.DOCKER_KEY }}
