name: Docker Build and Push

on:
  workflow_call:
    inputs:
      dockerhub_username:
        required: true
        type: string
      dockerhub_key:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_key }}

      - name: Build Docker image
        run: docker build -t ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ github.sha }}
